### ISSUE TITLE
Add troupe fairness and culling delay

### ISSUE THREAD

**Issue by kwquick** [kquick/Thespian#12]
When using a troupe, it would be nice to spread the work across the available troupe workers rather than preferring a particular member.  This can help if the troupe workers are using other resources (e.g. a socket) because that also distributes the workload to those resources and prevents timeouts.

In addition, some sort of delay before killing idle troupe members would be useful to avoid the worst-case behavior of `idle_count=1` and a steady-state rate of 1.5 msgs/t, such that the second worker keeps getting created and destroyed continuously.  A small delay before killing troupe members will avoid the higher overhead of continually creating and destroying troupe members.

**Comment by kquick** [comment]
Available in release 3.9.9  (https://github.com/kquick/Thespian/releases/tag/thespian-3.9.9)
