### ISSUE TITLE
Is this the new way forward with Thespian?

### ISSUE THREAD

**Issue by potbunker** [kquick/Thespian#20]
What is the relationship with GoDaddy? Looks like this is the only repo moving forward. Is it merged back to GoDady's repo? Is PyPI packages oiut of this repo?

If these answers are clear on the README, more support can come easily...

**Comment by kquick** [comment]
Somewhat ironically, I had just removed this from the README recently, thinking that it might be old info, but I think you are right: this information is still relevant and useful, so I have reverted that commit.  

Please feel free to re-open this if you have any suggestions for other information that is not now covered in the README, and thank you for bringing this up!

**Comment by potbunker** [comment]
Thanks. I just discovered this, while looking for akka equivalent in python. Looking forward to learning more, and helping out, as well.

**Comment by kquick** [comment]
That sounds great, and welcome to Thespian!
