### ISSUE TITLE
Issue with remote system in Openstack VM

### ISSUE THREAD

**Issue by artemistomaras** [kquick/Thespian#22]
I want to make a Convention with the following parameters:

My local ip : 192.168.1.50
Ip of VM: 10.0.101.3
Floating ip of the VM: 192.168.1.180

in the capabilities of the remote node, I pass the following tuple
('Convention Address.IPv4', ('192.168.1.50', 1900))

I start the actor system in my machine, and the actor system inside the VM.
When I run the multi_system example provided by this repository, I see that the actors in my remote system are created.

The problem is that the actor(s) in my machine cannot communicate with the remote actor. By placing a print statement in the following function:

```
    def receiveMsg_str(self, message, sender):
        """Primary entry point for receiving strings that are to be encoded
           and analyzed.
        """

        # First, make sure the analyzer is present
        if not self.analyzer:
            self.analyzer = self.createActor(Analyzer)

        # Now send the input string to each encoder.  The encoders
        # already have the analyzer address to forward the result
        # to, but include the original sender's address so that
        # the analyzer knows where to send the response.

        for each in self.encoders:
            if not self.encoders[each]:
                self.encoders[each] = self.createActor(each)
            print('Sending message to encoder {} -> {}'.format(each, self.encoders[each]))
            self.send(self.encoders[each],
                      EncodeThis(message, sender, self.analyzer))
```

i get the following output:
`Sending message to encoder encoder.Base64Encoder -> ActorAddr-9-ActorAddr-(T|10.0.101.3:46684~10.0.101.3:10000)`

It seems that my local actorsystem is trying to communicate with the remote system with the IP `10.0.101.3` and not the floating IP `192.168.1.180` of the VM.  

One possible answer is to add the following in the start of the `receiveMsg_str` function:
`self.preRegisterRemoteSystem('192.168.1.180:10000', dict([("64bit encoder", True)]))`

Is the anyway around this approach?

**Comment by kquick** [comment]
Hi @artemistomaras ,

I apologize for not responding earlier: I was traveling this weekend and did not have connectivity.

The code that determines the address that should be used is here: https://github.com/kquick/Thespian/blob/master/thespian/system/transport/IPBase.py#L118-L157, and you can test this code by:

    $ python
    >>> from thespian.system.transport.IPBase import TCPv4ActorAddress
    >>> t = TCPv4ActorAddress(external=True)
    >>> t.sockname[0]

Essentially this opens a socket connection (but sends no data) to 8.8.8.8 and then determines the local end's address for the socket, which should be an externally-useable and routable IP address.

If I recall OpenStack's configuration, it will assign the local IP address (10.x.x.x) inside the VM and perform external translation for the publicly assigned address (192.x.x.x), but it does not necessarily configure the 192.x.x.x address within the VM.  You should probably check to see if this is the case with `$ ip addr` and if it is missing, I would recommend you add the 192.x.x.x address as an alias to the eth0 port (which will help many other network applications as well as Thespian).

For example, on CentOS7, you would do this by writing the following to `/etc/sysconfig/network-scripts/ifcfg-eth0:2` (here `2` is the second alias: use whatever unique number is appropriate for your system):

    DEVICE=eth0:2
    ONBOOT=yes
    BOOTPROTO=static
    IPADDR=192.168.1.180
    NETMASK=255.255.255.255

and then restart the networking (e.g. `sudo systemctl restart network`).  You may also need to set `DEFROUTE=no` in the `/etc/sysconfig/network-scripts/ifcfg-eth0` file.

Let me know if this helps,
  Kevin

**Comment by artemistomaras** [comment]
Your steps seem to be correct. I have some issues though but those are openstack related.

Thanks for your time :1st_place_medal:

**Comment by kquick** [comment]
You're welcome, and I'm glad that helped.  Please let me know if you encounter more Thespian issues.
