### ISSUE TITLE
Remotely calling a thespian actor from Akka

### ISSUE THREAD

**Issue by sathishbabu96** [kquick/Thespian#37]
Hi, Is there a possibility that a thespian actor can be looked up remotely from Akka and be able to send messages to the thespian actor?

**Comment by kquick** [comment]
Hi @sathishbabu96 ,

No, I'm sorry, but I don't think this is possible.  Thespian and Akka use very different message formats, so there would need to be significant work on one or the other to allow them to even exchange messages, and then they would still need a way to interact with each other's actor namespaces.

If you have ideas or plans for achieving this, I'm happy to discuss that, but at this point it's not really possible.

**Comment by sathishbabu96** [comment]
Hi @kquick, 
Thanks

**Comment by sathishbabu96** [comment]
Hi @kquick 

Thanks for the response. I don't have any ideas for implementing communication between Akka and Thespian right now. If I get any, we may start working around it!.
