### ISSUE TITLE
Document links still broken

### ISSUE THREAD

**Issue by kquick** [kquick/Thespian#4]
The initial problem with the document links described in https://github.com/godaddy/Thespian/issues/41 seems to be resolved, but internal links are still not working as targets: copying a link and trying to open it in a new window always just opens the last section of the document ("Footnotes" for the "Using Thespian" document).

**Comment by tjkluska** [comment]
Should be http://thespianpy.com/doc/using

**Comment by kquick** [comment]
The documentation links are now fixed, but I did need to adjust the static references: any URL reference to a specific documentation location should change "#h:..." to "#hH-...".  The problem turns out to be a limitation in jQuery (http://api.jquery.com/category/selectors/) which required escaping of the : character in the references.  

Fixed as of commit ed10ecf619200a2debba865ff33a2f50a50c327e.
