### ISSUE TITLE
Confusing typos in director help

### ISSUE THREAD

**Issue by rsippl** [kquick/Thespian#40]
https://github.com/kquick/Thespian/blob/9dba3452f07252032c2f48731531720ff7dd14f6/thespian/director.py#L687

"specifies the director for thespian internal" should read director**y**. Also make sure you escape the \t in "c:\Windows\temp" in the same help section, or it will be printed as a tab.

**Comment by pjz** [comment]
Fixed in d295738fcb6189c77cac1d517f325b9674145e55 ; closable.

**Comment by kquick** [comment]
Thanks, @pjz
