### ISSUE TITLE
Faulty rot13 implementation in examples/multi_system

### ISSUE THREAD

**Issue by rsippl** [kquick/Thespian#41]
https://github.com/kquick/Thespian/blob/9dba3452f07252032c2f48731531720ff7dd14f6/examples/multi_system/act1/encoder.py#L54

Does not compute ;) A solution would be
```
return ((val - ord('a') + 13) % 26) + ord('a')
```
(and the same for 'A' .. 'Z').

**Comment by kquick** [comment]
Ha, thanks!  Fixed in https://github.com/kquick/Thespian/commit/fb390dfcd6c0593a01cf3136d8d8dd2ba0049b42
