### ISSUE TITLE
@requireCapability decorator fails when testing for keys set to string values

### ISSUE THREAD

**Issue by flewellyn** [kquick/Thespian#5]
Following up from the groups discussion.  I found that using @requireCapability on an actor class, where I set the capability to a string value, but did not specify a specific string value in the decorator, caused actor creation to fail.

Here is a test script.

[decortest.py.txt](https://github.com/kquick/Thespian/files/1137351/decortest.py.txt)

**Comment by kwquick** [comment]
Fixed in release 3.8.0  (https://github.com/kquick/Thespian/releases/tag/thespian-3.8.0).
